[package]
name = "unnamed-common"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = { workspace = true }
unnamed-derive = { workspace = true }
cranelift-entity = { workspace = true }
papaya = "0.2.3"
boxcar = "0.2.14"